apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc-webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      type: app
  template:
    metadata:
      name: rs-pod
      labels:
        type: app
    spec:
      containers:
        - image: veeroo2011/my-app:1.2
          name: myapp
